/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GenieCard {
        /**
          * If url provided and true the whole card will be a link
         */
        "cardIsLink": boolean;
        "heading": string;
        /**
          * Open link in new window
         */
        "newWindow": boolean;
        /**
          * Don't alter style on hover
         */
        "noHover": boolean;
        "text": string;
        "url": string;
    }
    interface GenieStripe {
        /**
          * Number of blocks in the stripe
         */
        "numBlocks": number;
    }
}
declare global {
    interface HTMLGenieCardElement extends Components.GenieCard, HTMLStencilElement {
    }
    var HTMLGenieCardElement: {
        prototype: HTMLGenieCardElement;
        new (): HTMLGenieCardElement;
    };
    interface HTMLGenieStripeElement extends Components.GenieStripe, HTMLStencilElement {
    }
    var HTMLGenieStripeElement: {
        prototype: HTMLGenieStripeElement;
        new (): HTMLGenieStripeElement;
    };
    interface HTMLElementTagNameMap {
        "genie-card": HTMLGenieCardElement;
        "genie-stripe": HTMLGenieStripeElement;
    }
}
declare namespace LocalJSX {
    interface GenieCard {
        /**
          * If url provided and true the whole card will be a link
         */
        "cardIsLink"?: boolean;
        "heading"?: string;
        /**
          * Open link in new window
         */
        "newWindow"?: boolean;
        /**
          * Don't alter style on hover
         */
        "noHover"?: boolean;
        "text"?: string;
        "url"?: string;
    }
    interface GenieStripe {
        /**
          * Number of blocks in the stripe
         */
        "numBlocks"?: number;
    }
    interface IntrinsicElements {
        "genie-card": GenieCard;
        "genie-stripe": GenieStripe;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "genie-card": LocalJSX.GenieCard & JSXBase.HTMLAttributes<HTMLGenieCardElement>;
            "genie-stripe": LocalJSX.GenieStripe & JSXBase.HTMLAttributes<HTMLGenieStripeElement>;
        }
    }
}
